name: rok_us_alliance_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  share_plus: ^10.0.2
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  youtube_player_iframe: ^5.2.1
  flutter_naver_login: ^2.1.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/maga_with_rok_popup.png
    - assets/images/korea_flag.png
    - assets/images/usa_flag.png