// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmzRPYirMApAC9uyYuESjlWfVcQvfgjqE',
    appId: '1:190755458781:web:41604fdd7260a0c09cd534',
    messagingSenderId: '190755458781',
    projectId: 'rok-us-alliance-app',
    authDomain: 'rok-us-alliance-app.firebaseapp.com',
    storageBucket: 'rok-us-alliance-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGyxH_275rJJKIxSG_og1mmEy_aE9FGnE',
    appId: '1:190755458781:android:b4da145c2a7a521c9cd534',
    messagingSenderId: '190755458781',
    projectId: 'rok-us-alliance-app',
    storageBucket: 'rok-us-alliance-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8i3Bxyb8GvXs-xjzoI0bS_rTpmmB1JhE',
    appId: '1:190755458781:ios:af63f173f9bac8ff9cd534',
    messagingSenderId: '190755458781',
    projectId: 'rok-us-alliance-app',
    storageBucket: 'rok-us-alliance-app.firebasestorage.app',
    iosBundleId: 'com.example.rokUsAllianceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8i3Bxyb8GvXs-xjzoI0bS_rTpmmB1JhE',
    appId: '1:190755458781:ios:af63f173f9bac8ff9cd534',
    messagingSenderId: '190755458781',
    projectId: 'rok-us-alliance-app',
    storageBucket: 'rok-us-alliance-app.firebasestorage.app',
    iosBundleId: 'com.example.rokUsAllianceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmzRPYirMApAC9uyYuESjlWfVcQvfgjqE',
    appId: '1:190755458781:web:c60edc5225dd8d589cd534',
    messagingSenderId: '190755458781',
    projectId: 'rok-us-alliance-app',
    authDomain: 'rok-us-alliance-app.firebaseapp.com',
    storageBucket: 'rok-us-alliance-app.firebasestorage.app',
  );

}